# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos6"
  config.vm.box_check_update = false
  config.ssh.insert_key = false
  config.vm.network :private_network, ip: "10.0.33.33"

  config.omnibus.chef_version = :latest

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "../cookbooks"
    chef.roles_path = "./json"
    chef.add_role "tsuba-role"
  end

  config.vm.provision :serverspec do |spec|
    spec.pattern = "spec/localhost/*_spec.rb"
  end
end
